Added husky, prettier, and ESLint. Updated readme
ideastoo/globbr-paint pull request #1
Opened 2021-11-15 14:37 UTC by jgreen123

2021-11-19 12:35 UTC, jmoorer commented
Looks good but be sure to use this   as the command  ` "lint": "eslint \"src/**/*.{js,ts,tsx}\" --quiet --fix"`
For some reason the single quotes didn't work on my machine.  and the haveing src a the root avoids linting the dist and node_modules folders

2021-11-19 12:39 UTC, jmoorer requested changes

2021-11-19 12:39 UTC, jmoorer commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
Looks good but be sure to use this as the command "lint": "eslint \"src/**/*.{js,ts,tsx}\" --quiet --fix"
For some reason the single quotes didn't work on my machine. and the haveing src a the root avoids linting the dist and node_modules folders

2021-11-20 02:19 UTC, jgreen123 commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
good point. updated.

2021-11-20 02:20 UTC, merged